using CertMaster.Domain.Entities;
using CertMaster.Domain.Enums;

namespace CertMaster.Infrastructure.Persistence.Seed;

/// <summary>
/// Original practice questions written to cover common CompTIA A+ (220-1201, 220-1202)
/// and Network+ (N10-009) exam objectives. These are not copied from any CompTIA
/// material — they are independently authored study questions covering the same
/// general subject areas, in the same spirit as any third-party exam-prep book.
/// </summary>
public static class SeedQuestionBank
{
    public record SeedOption(string Text, bool IsCorrect);

    public record SeedQuestion(
        string Topic,
        string? Subtopic,
        Difficulty Difficulty,
        string Prompt,
        string Explanation,
        string? Reference,
        SeedOption[] Options);

    public static List<SeedQuestion> APlusCore1() => new()
    {
        new SeedQuestion("Mobile Devices", "Laptop Hardware", Difficulty.Easy,
            "Which laptop component is most commonly replaced by a user to increase available memory without professional repair tools?",
            "SO-DIMM memory modules are designed for easy end-user access on most laptops, unlike soldered components such as the CPU.",
            "A+ Core 1 — Mobile Devices",
            new[] {
                new SeedOption("SO-DIMM RAM module", true),
                new SeedOption("CPU", false),
                new SeedOption("Soldered eMMC storage", false),
                new SeedOption("Digitizer", false),
            }),
        new SeedQuestion("Mobile Devices", "Connectivity", Difficulty.Medium,
            "A user reports their phone will not pair with a new car stereo, but pairs fine with other devices. What is the most likely first troubleshooting step?",
            "Removing (forgetting) the previously paired connection and re-pairing resolves most Bluetooth pairing conflicts caused by stale cached credentials.",
            "A+ Core 1 — Mobile Device Connectivity",
            new[] {
                new SeedOption("Forget the device on both ends and re-pair", true),
                new SeedOption("Factory reset the phone", false),
                new SeedOption("Replace the phone's battery", false),
                new SeedOption("Update the car's entire infotainment firmware", false),
            }),
        new SeedQuestion("Networking", "Cabling", Difficulty.Easy,
            "Which cable category is the minimum typically required to reliably support 10 Gbps Ethernet over short distances?",
            "Cat 6a is rated for 10GBASE-T at full 100-meter distances; Cat 6 can support 10 Gbps only over shorter, limited runs.",
            "A+ Core 1 — Networking",
            new[] {
                new SeedOption("Cat 5e", false),
                new SeedOption("Cat 6a", true),
                new SeedOption("Cat 3", false),
                new SeedOption("RG-6 coaxial", false),
            }),
        new SeedQuestion("Networking", "Wireless Standards", Difficulty.Medium,
            "Which wireless standard introduced OFDMA to improve efficiency in dense, high-user environments?",
            "802.11ax (Wi-Fi 6) introduced OFDMA, allowing an access point to serve multiple clients simultaneously on subdivided channels.",
            "A+ Core 1 — Networking",
            new[] {
                new SeedOption("802.11n", false),
                new SeedOption("802.11ac", false),
                new SeedOption("802.11ax", true),
                new SeedOption("802.11g", false),
            }),
        new SeedQuestion("Hardware", "Storage Devices", Difficulty.Easy,
            "Which storage interface offers the highest theoretical throughput for a consumer desktop today?",
            "NVMe drives running over PCIe lanes offer far higher bandwidth than SATA, USB 2.0, or eSATA interfaces.",
            "A+ Core 1 — Hardware",
            new[] {
                new SeedOption("SATA III", false),
                new SeedOption("NVMe over PCIe", true),
                new SeedOption("USB 2.0", false),
                new SeedOption("eSATA", false),
            }),
        new SeedQuestion("Hardware", "Power Supplies", Difficulty.Medium,
            "A technician is selecting a power supply for a workstation with a high-end GPU. Which rating is most directly relevant to whether the PSU can support that GPU?",
            "Continuous wattage output on the +12V rail(s) determines whether a PSU can reliably feed a power-hungry GPU; the 80 Plus badge only measures efficiency, not capacity.",
            "A+ Core 1 — Hardware",
            new[] {
                new SeedOption("80 Plus certification tier", false),
                new SeedOption("Continuous wattage on the +12V rail", true),
                new SeedOption("Case form factor", false),
                new SeedOption("Number of SATA power connectors", false),
            }),
        new SeedQuestion("Virtualization and Cloud", "Cloud Concepts", Difficulty.Medium,
            "A company wants to rent virtual machines and manage the OS and applications themselves, while the provider manages the physical hardware. Which cloud model is this?",
            "Infrastructure as a Service (IaaS) provides raw compute, storage, and networking; the customer manages the OS, runtime, and applications.",
            "A+ Core 1 — Virtualization and Cloud Computing",
            new[] {
                new SeedOption("SaaS", false),
                new SeedOption("PaaS", false),
                new SeedOption("IaaS", true),
                new SeedOption("DaaS", false),
            }),
        new SeedQuestion("Virtualization and Cloud", "Virtualization", Difficulty.Hard,
            "Which type of hypervisor runs directly on physical hardware without a host operating system, and is typically used in enterprise datacenters?",
            "A Type 1 (bare-metal) hypervisor runs directly on hardware, offering better performance and security isolation than a Type 2 hypervisor hosted inside a general-purpose OS.",
            "A+ Core 1 — Virtualization and Cloud Computing",
            new[] {
                new SeedOption("Type 2 hypervisor", false),
                new SeedOption("Type 1 hypervisor", true),
                new SeedOption("Container runtime", false),
                new SeedOption("Emulator", false),
            }),
        new SeedQuestion("Hardware and Network Troubleshooting", "Diagnostics", Difficulty.Medium,
            "A desktop powers on, fans spin, but there is no video output and no POST beep. What is the most efficient next troubleshooting step?",
            "Reseating RAM (and testing one stick at a time in known-good slots) is a fast, low-risk step that resolves a large share of no-POST issues before moving to more invasive steps.",
            "A+ Core 1 — Troubleshooting",
            new[] {
                new SeedOption("Reseat the RAM modules", true),
                new SeedOption("Replace the power supply immediately", false),
                new SeedOption("Reinstall the operating system", false),
                new SeedOption("Replace the case fans", false),
            }),
        new SeedQuestion("Hardware and Network Troubleshooting", "Printers", Difficulty.Easy,
            "A laser printer produces pages with a repeating vertical smear at a consistent interval down the page. What component is most likely at fault?",
            "A repeating defect at a fixed interval strongly indicates a damaged or contaminated drum, since the defect repeats every one drum rotation.",
            "A+ Core 1 — Troubleshooting",
            new[] {
                new SeedOption("Damaged imaging drum", true),
                new SeedOption("Empty toner cartridge", false),
                new SeedOption("Faulty USB cable", false),
                new SeedOption("Incorrect paper size setting", false),
            }),
    };

    public static List<SeedQuestion> APlusCore2() => new()
    {
        new SeedQuestion("Operating Systems", "Windows", Difficulty.Easy,
            "Which built-in Windows tool would an administrator use to view detailed hardware and driver information for troubleshooting?",
            "Device Manager lists all detected hardware, driver versions, and status codes, making it the standard first stop for hardware/driver issues.",
            "A+ Core 2 — Operating Systems",
            new[] {
                new SeedOption("Device Manager", true),
                new SeedOption("Task Scheduler", false),
                new SeedOption("Disk Cleanup", false),
                new SeedOption("Character Map", false),
            }),
        new SeedQuestion("Operating Systems", "Command Line", Difficulty.Medium,
            "Which Windows command-line utility is used to display and modify the IP configuration of network adapters?",
            "ipconfig displays current TCP/IP configuration; /release and /renew flags force a new DHCP lease.",
            "A+ Core 2 — Operating Systems",
            new[] {
                new SeedOption("ipconfig", true),
                new SeedOption("chkdsk", false),
                new SeedOption("sfc", false),
                new SeedOption("diskpart", false),
            }),
        new SeedQuestion("Security", "Authentication", Difficulty.Medium,
            "Which authentication factor category does a fingerprint scan belong to?",
            "A fingerprint is 'something you are' — an inherence factor — distinct from knowledge factors (passwords) or possession factors (security tokens).",
            "A+ Core 2 — Security",
            new[] {
                new SeedOption("Something you know", false),
                new SeedOption("Something you have", false),
                new SeedOption("Something you are", true),
                new SeedOption("Somewhere you are", false),
            }),
        new SeedQuestion("Security", "Malware", Difficulty.Hard,
            "A user's files have all been renamed with an unfamiliar extension and a message demands payment for a decryption key. What type of malware is this?",
            "This is the defining behavior of ransomware: encrypting victim files and demanding payment for the decryption key.",
            "A+ Core 2 — Security",
            new[] {
                new SeedOption("Ransomware", true),
                new SeedOption("Trojan", false),
                new SeedOption("Rootkit", false),
                new SeedOption("Adware", false),
            }),
        new SeedQuestion("Security", "Physical Security", Difficulty.Easy,
            "Which physical security control specifically prevents an unauthorized person from following an authorized person through a secure door?",
            "A mantrap (or access-controlled vestibule) physically prevents tailgating by only allowing one verified person through at a time.",
            "A+ Core 2 — Security",
            new[] {
                new SeedOption("Mantrap", true),
                new SeedOption("Privacy screen", false),
                new SeedOption("Cable lock", false),
                new SeedOption("Badge reader alone", false),
            }),
        new SeedQuestion("Software Troubleshooting", "Windows Issues", Difficulty.Medium,
            "A Windows PC displays a 'Blue Screen of Death' referencing a driver file. What is a reasonable first remediation step?",
            "Booting into Safe Mode and rolling back or removing the recently updated driver is the standard first response to a driver-related BSOD.",
            "A+ Core 2 — Software Troubleshooting",
            new[] {
                new SeedOption("Boot into Safe Mode and roll back the driver", true),
                new SeedOption("Immediately reinstall Windows", false),
                new SeedOption("Replace the motherboard", false),
                new SeedOption("Disable the network adapter", false),
            }),
        new SeedQuestion("Software Troubleshooting", "Mobile OS", Difficulty.Easy,
            "A mobile device is running noticeably slower than usual and several unfamiliar apps have appeared. What should be checked first?",
            "Reviewing recently installed apps and permissions is the fastest way to identify unauthorized or malicious software causing the slowdown.",
            "A+ Core 2 — Software Troubleshooting",
            new[] {
                new SeedOption("Recently installed apps and their permissions", true),
                new SeedOption("Screen brightness setting", false),
                new SeedOption("Wallpaper resolution", false),
                new SeedOption("Bluetooth pairing history", false),
            }),
        new SeedQuestion("Operational Procedures", "Documentation", Difficulty.Medium,
            "Before making a significant configuration change to a production server, what should a technician create or follow?",
            "A documented change management process (with a rollback plan) reduces risk and ensures changes are tracked and reversible.",
            "A+ Core 2 — Operational Procedures",
            new[] {
                new SeedOption("A change management request with a rollback plan", true),
                new SeedOption("A verbal agreement with a coworker", false),
                new SeedOption("No documentation is needed for small changes", false),
                new SeedOption("A social media post announcing the change", false),
            }),
        new SeedQuestion("Operational Procedures", "Safety", Difficulty.Easy,
            "What is the primary purpose of an ESD strap when working inside a computer case?",
            "An ESD strap grounds the technician to prevent static discharge from damaging sensitive electronic components.",
            "A+ Core 2 — Operational Procedures",
            new[] {
                new SeedOption("To prevent electrostatic discharge from damaging components", true),
                new SeedOption("To hold cables out of the way", false),
                new SeedOption("To measure voltage", false),
                new SeedOption("To ground the power supply to the case", false),
            }),
        new SeedQuestion("Operational Procedures", "Backup Strategy", Difficulty.Medium,
            "Which backup strategy stores backups at a physically separate location from the primary site to protect against site-wide disasters?",
            "Off-site backups protect against fire, flood, theft, or other events that could destroy both the production data and a local backup simultaneously.",
            "A+ Core 2 — Operational Procedures",
            new[] {
                new SeedOption("Off-site backup", true),
                new SeedOption("Local incremental backup only", false),
                new SeedOption("RAID 0 mirroring", false),
                new SeedOption("Snapshot on the same disk", false),
            }),
    };

    public static List<SeedQuestion> NetworkPlus() => new()
    {
        new SeedQuestion("Networking Concepts", "IP Addressing", Difficulty.Medium,
            "A technician needs to subnet a /24 network into 4 equal subnets. What subnet mask should be used?",
            "Splitting a /24 into 4 equal subnets requires borrowing 2 bits, giving a /26 mask (255.255.255.192), which yields 4 subnets of 64 addresses each.",
            "Network+ — Objective 1.4",
            new[] {
                new SeedOption("255.255.255.128", false),
                new SeedOption("255.255.255.192", true),
                new SeedOption("255.255.255.224", false),
                new SeedOption("255.255.255.240", false),
            }),
        new SeedQuestion("Networking Concepts", "OSI Model", Difficulty.Easy,
            "At which OSI layer does a standard Ethernet switch primarily operate when forwarding frames based on MAC address?",
            "Switches forward traffic based on MAC addresses, which are examined and used at Layer 2 (the Data Link layer).",
            "Network+ — Objective 1.1",
            new[] {
                new SeedOption("Layer 1 — Physical", false),
                new SeedOption("Layer 2 — Data Link", true),
                new SeedOption("Layer 3 — Network", false),
                new SeedOption("Layer 4 — Transport", false),
            }),
        new SeedQuestion("Networking Concepts", "Ports and Protocols", Difficulty.Medium,
            "Which port is used by DNS for standard name resolution queries?",
            "DNS uses port 53 for both UDP (typical queries) and TCP (zone transfers and larger responses).",
            "Network+ — Objective 1.5",
            new[] {
                new SeedOption("Port 25", false),
                new SeedOption("Port 53", true),
                new SeedOption("Port 443", false),
                new SeedOption("Port 3389", false),
            }),
        new SeedQuestion("Infrastructure", "Cabling Standards", Difficulty.Medium,
            "Which fiber connector type uses a push-pull mechanism and is common in modern datacenter deployments?",
            "The LC connector uses a compact push-pull latch and is widely used in high-density datacenter patch panels, in contrast to the older screw-on SC or ST connectors.",
            "Network+ — Objective 2.1",
            new[] {
                new SeedOption("ST connector", false),
                new SeedOption("SC connector", false),
                new SeedOption("LC connector", true),
                new SeedOption("BNC connector", false),
            }),
        new SeedQuestion("Infrastructure", "Wireless", Difficulty.Hard,
            "Two nearby access points on overlapping 2.4 GHz channels are causing interference. Which channel plan avoids overlap for three co-located APs?",
            "Channels 1, 6, and 11 are the only non-overlapping channels in the 2.4 GHz band in most regulatory domains, making them the standard plan for adjacent APs.",
            "Network+ — Objective 2.4",
            new[] {
                new SeedOption("Channels 1, 6, 11", true),
                new SeedOption("Channels 2, 5, 9", false),
                new SeedOption("Channels 1, 2, 3", false),
                new SeedOption("Channels 6, 7, 8", false),
            }),
        new SeedQuestion("Network Operations", "Monitoring", Difficulty.Medium,
            "Which protocol is commonly used to collect performance and status data from network devices for centralized monitoring?",
            "SNMP (Simple Network Management Protocol) is the standard protocol for polling and receiving status/performance data from managed network devices.",
            "Network+ — Objective 3.1",
            new[] {
                new SeedOption("SNMP", true),
                new SeedOption("FTP", false),
                new SeedOption("SMTP", false),
                new SeedOption("NTP", false),
            }),
        new SeedQuestion("Network Operations", "Disaster Recovery", Difficulty.Medium,
            "What metric describes the maximum acceptable amount of data loss, measured in time, following an outage?",
            "Recovery Point Objective (RPO) defines how much data (in time) an organization can afford to lose, which drives backup frequency decisions.",
            "Network+ — Objective 3.2",
            new[] {
                new SeedOption("RTO", false),
                new SeedOption("RPO", true),
                new SeedOption("MTTR", false),
                new SeedOption("MTBF", false),
            }),
        new SeedQuestion("Network Security", "Threats", Difficulty.Medium,
            "An attacker floods a server with more connection requests than it can handle, making it unavailable to legitimate users. What is this attack called?",
            "This describes a Denial of Service (DoS) attack; when performed from multiple sources simultaneously, it is a Distributed DoS (DDoS).",
            "Network+ — Objective 4.1",
            new[] {
                new SeedOption("Denial of Service", true),
                new SeedOption("ARP spoofing", false),
                new SeedOption("DNS poisoning", false),
                new SeedOption("VLAN hopping", false),
            }),
        new SeedQuestion("Network Security", "Hardening", Difficulty.Easy,
            "Which practice most directly reduces a device's attack surface by removing unused functionality?",
            "Disabling unused ports, services, and protocols directly shrinks the number of possible entry points an attacker can exploit.",
            "Network+ — Objective 4.3",
            new[] {
                new SeedOption("Disabling unused ports and services", true),
                new SeedOption("Increasing Wi-Fi transmit power", false),
                new SeedOption("Enabling guest network broadcast", false),
                new SeedOption("Installing more applications", false),
            }),
        new SeedQuestion("Network Troubleshooting", "Methodology", Difficulty.Medium,
            "After identifying the probable cause of a network issue, what is the next recommended step in standard troubleshooting methodology?",
            "The standard methodology moves from identifying probable cause to establishing a theory, then testing that theory before implementing a full solution.",
            "Network+ — Objective 5.1",
            new[] {
                new SeedOption("Establish a theory of probable cause and test it", true),
                new SeedOption("Immediately replace all hardware", false),
                new SeedOption("Close the ticket without further action", false),
                new SeedOption("Escalate without gathering any information", false),
            }),
        new SeedQuestion("Network Troubleshooting", "Tools", Difficulty.Easy,
            "Which command-line tool traces the path packets take across multiple routers to a destination?",
            "traceroute (or tracert on Windows) reports each hop between source and destination, helping isolate where latency or loss is occurring.",
            "Network+ — Objective 5.2",
            new[] {
                new SeedOption("traceroute / tracert", true),
                new SeedOption("nslookup", false),
                new SeedOption("netstat", false),
                new SeedOption("ping only", false),
            }),
        new SeedQuestion("Network Troubleshooting", "IP Configuration", Difficulty.Easy,
            "A Windows workstation assigns itself an address beginning with 169.254 after startup. What is the most likely cause?",
            "A 169.254.x.x APIPA address is automatically assigned when the workstation cannot obtain a valid lease from a DHCP server.",
            "Network+ — Objective 5.5",
            new[] {
                new SeedOption("The DHCP server could not be reached", true),
                new SeedOption("The DNS server resolved the wrong hostname", false),
                new SeedOption("The default gateway is using NAT", false),
                new SeedOption("The switch port negotiated full duplex", false),
            }),
    };
}
