import { useState } from "react";
import { useAdminCertifications, useUpdateAdminCertification } from "../../hooks/useApiData";
import { Card, SectionHeading, Badge } from "../../components/ui/Primitives";
import { Button } from "../../components/ui/Button";

export default function AdminCertifications() {
  const {data,isLoading}=useAdminCertifications(); const update=useUpdateAdminCertification(); const [editing,setEditing]=useState<string|null>(null); const [draft,setDraft]=useState<any>(null);
  const begin=(c:any)=>{setEditing(c.id);setDraft({...c})};
  const save=()=>update.mutate({id:editing!,data:{code:draft.code,name:draft.name,vendor:draft.vendor,version:draft.version,description:draft.description,isActive:draft.isActive,examDurationMinutes:Number(draft.examDurationMinutes),passingScorePercent:Number(draft.passingScorePercent),mockExamQuestionCount:Number(draft.mockExamQuestionCount)}},{onSuccess:()=>setEditing(null)});
  return <div className="space-y-6"><SectionHeading title="Certifications" description="Manage certification metadata, availability, and mock-exam rules."/>{isLoading?<p>Loading certifications...</p>:<div className="space-y-4">{data?.map(c=>editing===c.id?<Card key={c.id} className="p-5 space-y-4"><div className="grid md:grid-cols-2 gap-3"><input value={draft.name} onChange={e=>setDraft((d:any)=>({...d,name:e.target.value}))} className="h-10 px-3 border rounded-md"/><input value={draft.code} onChange={e=>setDraft((d:any)=>({...d,code:e.target.value}))} className="h-10 px-3 border rounded-md"/><input value={draft.vendor} onChange={e=>setDraft((d:any)=>({...d,vendor:e.target.value}))} className="h-10 px-3 border rounded-md"/><input value={draft.version} onChange={e=>setDraft((d:any)=>({...d,version:e.target.value}))} className="h-10 px-3 border rounded-md"/><input type="number" value={draft.examDurationMinutes} onChange={e=>setDraft((d:any)=>({...d,examDurationMinutes:e.target.value}))} placeholder="Exam minutes" className="h-10 px-3 border rounded-md"/><input type="number" value={draft.passingScorePercent} onChange={e=>setDraft((d:any)=>({...d,passingScorePercent:e.target.value}))} placeholder="Passing %" className="h-10 px-3 border rounded-md"/><input type="number" value={draft.mockExamQuestionCount} onChange={e=>setDraft((d:any)=>({...d,mockExamQuestionCount:e.target.value}))} placeholder="Mock questions" className="h-10 px-3 border rounded-md"/></div><textarea value={draft.description} onChange={e=>setDraft((d:any)=>({...d,description:e.target.value}))} rows={3} className="w-full p-3 border rounded-md"/><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={draft.isActive} onChange={e=>setDraft((d:any)=>({...d,isActive:e.target.checked}))}/> Available to learners</label><div className="flex gap-2"><Button onClick={save} disabled={update.isPending}>Save</Button><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button></div></Card>:<Card key={c.id} className="p-5"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{c.name}</h3><Badge tone={c.isActive?"success":"neutral"}>{c.isActive?"Active":"Inactive"}</Badge></div><p className="text-sm text-text-secondary mt-1">{c.vendor} · {c.code} · {c.version}</p><p className="text-xs text-text-secondary mt-2">{c.questionCount} published questions · {c.topicCount} topics · {c.examDurationMinutes} min · {c.passingScorePercent}% pass · {c.mockExamQuestionCount} mock questions</p></div><Button size="sm" variant="secondary" onClick={()=>begin(c)}>Edit</Button></div></Card>)}</div>}</div>;
}
