import { useState } from "react";
import { Link } from "react-router-dom";
import { useAdminCertifications, useAdminQuestions } from "../../hooks/useApiData";
import { Card, SectionHeading, Badge } from "../../components/ui/Primitives";
import { Button } from "../../components/ui/Button";

export default function Questions() {
  const [search,setSearch]=useState(""); const [certificationId,setCertificationId]=useState(""); const [status,setStatus]=useState(""); const [difficulty,setDifficulty]=useState(""); const [page,setPage]=useState(1);
  const {data: certifications}=useAdminCertifications(); const {data,isLoading}=useAdminQuestions({search,certificationId,status,difficulty,page,pageSize:25});
  return <div className="space-y-6"><SectionHeading title="Live question bank" description="Search and edit questions that are already published or staged in the live bank." />
    <Card className="p-4 grid gap-3 md:grid-cols-4"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search question or topic" className="h-11 px-3 rounded-md border"/><select value={certificationId} onChange={e=>{setCertificationId(e.target.value);setPage(1)}} className="h-11 px-3 rounded-md border"><option value="">All certifications</option>{certifications?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="h-11 px-3 rounded-md border"><option value="">All statuses</option><option>Published</option><option>Draft</option><option>Flagged</option></select><select value={difficulty} onChange={e=>{setDifficulty(e.target.value);setPage(1)}} className="h-11 px-3 rounded-md border"><option value="">All difficulty</option><option>Easy</option><option>Medium</option><option>Hard</option></select></Card>
    <Card className="p-0 overflow-x-auto">{isLoading?<p className="p-5">Loading questions...</p>:<><table className="w-full text-sm"><thead><tr className="text-left bg-bg-alt"><th className="p-3">Question</th><th>Certification</th><th>Topic</th><th>Difficulty</th><th>Status</th><th></th></tr></thead><tbody>{data?.items.map(q=><tr key={q.id} className="border-t"><td className="p-3 max-w-xl"><div className="font-medium truncate">{q.prompt}</div><div className="text-xs text-text-secondary">{q.questionType}</div></td><td>{q.certificationName}</td><td>{q.topic}</td><td>{q.difficulty}</td><td><Badge tone={q.status === "Published" ? "success" : q.status === "Flagged" ? "warning" : "neutral"}>{q.status}</Badge></td><td><Link to={`/admin/questions/${q.id}`} className="text-brand-primary font-medium hover:underline">Edit</Link></td></tr>)}{data?.items.length===0&&<tr><td colSpan={6} className="p-8 text-center text-text-secondary">No questions found.</td></tr>}</tbody></table><div className="p-4 flex justify-end items-center gap-2"><Button size="sm" variant="secondary" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</Button><span className="text-sm">Page {page} of {data?.totalPages||1}</span><Button size="sm" variant="secondary" disabled={page>=(data?.totalPages||1)} onClick={()=>setPage(p=>p+1)}>Next</Button></div></>}</Card>
  </div>;
}
